// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package hotty

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *Area) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.Col, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Col")
				return
			}
		case "r":
			z.Row, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "Row")
				return
			}
		case "w":
			z.W, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "W")
				return
			}
		case "h":
			z.H, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "H")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Area) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 4
	// write "c"
	err = en.Append(0x84, 0xa1, 0x63)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Col)
	if err != nil {
		err = msgp.WrapError(err, "Col")
		return
	}
	// write "r"
	err = en.Append(0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt(z.Row)
	if err != nil {
		err = msgp.WrapError(err, "Row")
		return
	}
	// write "w"
	err = en.Append(0xa1, 0x77)
	if err != nil {
		return
	}
	err = en.WriteInt(z.W)
	if err != nil {
		err = msgp.WrapError(err, "W")
		return
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteInt(z.H)
	if err != nil {
		err = msgp.WrapError(err, "H")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Area) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize + 2 + msgp.IntSize + 2 + msgp.IntSize + 2 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Caps) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "v":
			z.V, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "V")
				return
			}
		case "ops":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Ops")
				return
			}
			if cap(z.Ops) >= int(zb0002) {
				z.Ops = (z.Ops)[:zb0002]
			} else {
				z.Ops = make([]string, zb0002)
			}
			for za0001 := range z.Ops {
				z.Ops[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Ops", za0001)
					return
				}
			}
		case "events":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Events")
				return
			}
			if cap(z.Events) >= int(zb0003) {
				z.Events = (z.Events)[:zb0003]
			} else {
				z.Events = make([]string, zb0003)
			}
			for za0002 := range z.Events {
				z.Events[za0002], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Events", za0002)
					return
				}
			}
		case "cell":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Cell")
					return
				}
				z.Cell = nil
			} else {
				if z.Cell == nil {
					z.Cell = new(Cell)
				}
				var zb0004 uint32
				zb0004, err = dc.ReadMapHeader()
				if err != nil {
					err = msgp.WrapError(err, "Cell")
					return
				}
				for zb0004 > 0 {
					zb0004--
					field, err = dc.ReadMapKeyPtr()
					if err != nil {
						err = msgp.WrapError(err, "Cell")
						return
					}
					switch msgp.UnsafeString(field) {
					case "w":
						z.Cell.W, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Cell", "W")
							return
						}
					case "h":
						z.Cell.H, err = dc.ReadInt()
						if err != nil {
							err = msgp.WrapError(err, "Cell", "H")
							return
						}
					default:
						err = dc.Skip()
						if err != nil {
							err = msgp.WrapError(err, "Cell")
							return
						}
					}
				}
			}
		case "scale":
			z.Scale, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "Scale")
				return
			}
		case "scheme":
			z.Scheme, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Scheme")
				return
			}
		case "limits":
			var zb0005 uint32
			zb0005, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Limits")
				return
			}
			if z.Limits == nil {
				z.Limits = make(map[string]int, zb0005)
			} else if len(z.Limits) > 0 {
				clear(z.Limits)
			}
			for zb0005 > 0 {
				zb0005--
				var za0003 string
				za0003, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Limits")
					return
				}
				var za0004 int
				za0004, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Limits", za0003)
					return
				}
				z.Limits[za0003] = za0004
			}
		case "net":
			var zb0006 uint32
			zb0006, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Net")
				return
			}
			if z.Net == nil {
				z.Net = make(map[string][]string, zb0006)
			} else if len(z.Net) > 0 {
				clear(z.Net)
			}
			for zb0006 > 0 {
				zb0006--
				var za0005 string
				za0005, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Net")
					return
				}
				var za0006 []string
				var zb0007 uint32
				zb0007, err = dc.ReadArrayHeader()
				if err != nil {
					err = msgp.WrapError(err, "Net", za0005)
					return
				}
				if cap(za0006) >= int(zb0007) {
					za0006 = (za0006)[:zb0007]
				} else {
					za0006 = make([]string, zb0007)
				}
				for za0007 := range za0006 {
					za0006[za0007], err = dc.ReadString()
					if err != nil {
						err = msgp.WrapError(err, "Net", za0005, za0007)
						return
					}
				}
				z.Net[za0005] = za0006
			}
		case "scroll":
			z.Scroll, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Scroll")
				return
			}
		case "passthrough":
			z.Passthrough, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Passthrough")
				return
			}
		case "steps":
			z.Steps, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Steps")
				return
			}
		case "host":
			z.Host, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Host")
				return
			}
		case "version":
			z.Version, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *Caps) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(13)
	var zb0001Mask uint16 /* 13 bits */
	_ = zb0001Mask
	if z.Ops == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Events == nil {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Cell == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Scale == 0 {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	if z.Scheme == "" {
		zb0001Len--
		zb0001Mask |= 0x20
	}
	if z.Limits == nil {
		zb0001Len--
		zb0001Mask |= 0x40
	}
	if z.Net == nil {
		zb0001Len--
		zb0001Mask |= 0x80
	}
	if z.Scroll == false {
		zb0001Len--
		zb0001Mask |= 0x100
	}
	if z.Passthrough == false {
		zb0001Len--
		zb0001Mask |= 0x200
	}
	if z.Steps == false {
		zb0001Len--
		zb0001Mask |= 0x400
	}
	if z.Host == "" {
		zb0001Len--
		zb0001Mask |= 0x800
	}
	if z.Version == "" {
		zb0001Len--
		zb0001Mask |= 0x1000
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "v"
		err = en.Append(0xa1, 0x76)
		if err != nil {
			return
		}
		err = en.WriteString(z.V)
		if err != nil {
			err = msgp.WrapError(err, "V")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "ops"
			err = en.Append(0xa3, 0x6f, 0x70, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Ops)))
			if err != nil {
				err = msgp.WrapError(err, "Ops")
				return
			}
			for za0001 := range z.Ops {
				err = en.WriteString(z.Ops[za0001])
				if err != nil {
					err = msgp.WrapError(err, "Ops", za0001)
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "events"
			err = en.Append(0xa6, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x73)
			if err != nil {
				return
			}
			err = en.WriteArrayHeader(uint32(len(z.Events)))
			if err != nil {
				err = msgp.WrapError(err, "Events")
				return
			}
			for za0002 := range z.Events {
				err = en.WriteString(z.Events[za0002])
				if err != nil {
					err = msgp.WrapError(err, "Events", za0002)
					return
				}
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "cell"
			err = en.Append(0xa4, 0x63, 0x65, 0x6c, 0x6c)
			if err != nil {
				return
			}
			if z.Cell == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				// map header, size 2
				// write "w"
				err = en.Append(0x82, 0xa1, 0x77)
				if err != nil {
					return
				}
				err = en.WriteInt(z.Cell.W)
				if err != nil {
					err = msgp.WrapError(err, "Cell", "W")
					return
				}
				// write "h"
				err = en.Append(0xa1, 0x68)
				if err != nil {
					return
				}
				err = en.WriteInt(z.Cell.H)
				if err != nil {
					err = msgp.WrapError(err, "Cell", "H")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "scale"
			err = en.Append(0xa5, 0x73, 0x63, 0x61, 0x6c, 0x65)
			if err != nil {
				return
			}
			err = en.WriteFloat64(z.Scale)
			if err != nil {
				err = msgp.WrapError(err, "Scale")
				return
			}
		}
		if (zb0001Mask & 0x20) == 0 { // if not omitted
			// write "scheme"
			err = en.Append(0xa6, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65)
			if err != nil {
				return
			}
			err = en.WriteString(z.Scheme)
			if err != nil {
				err = msgp.WrapError(err, "Scheme")
				return
			}
		}
		if (zb0001Mask & 0x40) == 0 { // if not omitted
			// write "limits"
			err = en.Append(0xa6, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x73)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Limits)))
			if err != nil {
				err = msgp.WrapError(err, "Limits")
				return
			}
			for za0003, za0004 := range z.Limits {
				err = en.WriteString(za0003)
				if err != nil {
					err = msgp.WrapError(err, "Limits")
					return
				}
				err = en.WriteInt(za0004)
				if err != nil {
					err = msgp.WrapError(err, "Limits", za0003)
					return
				}
			}
		}
		if (zb0001Mask & 0x80) == 0 { // if not omitted
			// write "net"
			err = en.Append(0xa3, 0x6e, 0x65, 0x74)
			if err != nil {
				return
			}
			err = en.WriteMapHeader(uint32(len(z.Net)))
			if err != nil {
				err = msgp.WrapError(err, "Net")
				return
			}
			for za0005, za0006 := range z.Net {
				err = en.WriteString(za0005)
				if err != nil {
					err = msgp.WrapError(err, "Net")
					return
				}
				err = en.WriteArrayHeader(uint32(len(za0006)))
				if err != nil {
					err = msgp.WrapError(err, "Net", za0005)
					return
				}
				for za0007 := range za0006 {
					err = en.WriteString(za0006[za0007])
					if err != nil {
						err = msgp.WrapError(err, "Net", za0005, za0007)
						return
					}
				}
			}
		}
		if (zb0001Mask & 0x100) == 0 { // if not omitted
			// write "scroll"
			err = en.Append(0xa6, 0x73, 0x63, 0x72, 0x6f, 0x6c, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteBool(z.Scroll)
			if err != nil {
				err = msgp.WrapError(err, "Scroll")
				return
			}
		}
		if (zb0001Mask & 0x200) == 0 { // if not omitted
			// write "passthrough"
			err = en.Append(0xab, 0x70, 0x61, 0x73, 0x73, 0x74, 0x68, 0x72, 0x6f, 0x75, 0x67, 0x68)
			if err != nil {
				return
			}
			err = en.WriteBool(z.Passthrough)
			if err != nil {
				err = msgp.WrapError(err, "Passthrough")
				return
			}
		}
		if (zb0001Mask & 0x400) == 0 { // if not omitted
			// write "steps"
			err = en.Append(0xa5, 0x73, 0x74, 0x65, 0x70, 0x73)
			if err != nil {
				return
			}
			err = en.WriteBool(z.Steps)
			if err != nil {
				err = msgp.WrapError(err, "Steps")
				return
			}
		}
		if (zb0001Mask & 0x800) == 0 { // if not omitted
			// write "host"
			err = en.Append(0xa4, 0x68, 0x6f, 0x73, 0x74)
			if err != nil {
				return
			}
			err = en.WriteString(z.Host)
			if err != nil {
				err = msgp.WrapError(err, "Host")
				return
			}
		}
		if (zb0001Mask & 0x1000) == 0 { // if not omitted
			// write "version"
			err = en.Append(0xa7, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e)
			if err != nil {
				return
			}
			err = en.WriteString(z.Version)
			if err != nil {
				err = msgp.WrapError(err, "Version")
				return
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *Caps) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.V) + 4 + msgp.ArrayHeaderSize
	for za0001 := range z.Ops {
		s += msgp.StringPrefixSize + len(z.Ops[za0001])
	}
	s += 7 + msgp.ArrayHeaderSize
	for za0002 := range z.Events {
		s += msgp.StringPrefixSize + len(z.Events[za0002])
	}
	s += 5
	if z.Cell == nil {
		s += msgp.NilSize
	} else {
		s += 1 + 2 + msgp.IntSize + 2 + msgp.IntSize
	}
	s += 6 + msgp.Float64Size + 7 + msgp.StringPrefixSize + len(z.Scheme) + 7 + msgp.MapHeaderSize
	if z.Limits != nil {
		for za0003, za0004 := range z.Limits {
			_ = za0004
			s += msgp.StringPrefixSize + len(za0003) + msgp.IntSize
		}
	}
	s += 4 + msgp.MapHeaderSize
	if z.Net != nil {
		for za0005, za0006 := range z.Net {
			_ = za0006
			s += msgp.StringPrefixSize + len(za0005) + msgp.ArrayHeaderSize
			for za0007 := range za0006 {
				s += msgp.StringPrefixSize + len(za0006[za0007])
			}
		}
	}
	s += 7 + msgp.BoolSize + 12 + msgp.BoolSize + 6 + msgp.BoolSize + 5 + msgp.StringPrefixSize + len(z.Host) + 8 + msgp.StringPrefixSize + len(z.Version)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Cell) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "w":
			z.W, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "W")
				return
			}
		case "h":
			z.H, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "H")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Cell) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "w"
	err = en.Append(0x82, 0xa1, 0x77)
	if err != nil {
		return
	}
	err = en.WriteInt(z.W)
	if err != nil {
		err = msgp.WrapError(err, "W")
		return
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteInt(z.H)
	if err != nil {
		err = msgp.WrapError(err, "H")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Cell) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize + 2 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *Size) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "w":
			z.W, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "W")
				return
			}
		case "h":
			z.H, err = dc.ReadFloat64()
			if err != nil {
				err = msgp.WrapError(err, "H")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z Size) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 2
	// write "w"
	err = en.Append(0x82, 0xa1, 0x77)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.W)
	if err != nil {
		err = msgp.WrapError(err, "W")
		return
	}
	// write "h"
	err = en.Append(0xa1, 0x68)
	if err != nil {
		return
	}
	err = en.WriteFloat64(z.H)
	if err != nil {
		err = msgp.WrapError(err, "H")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z Size) Msgsize() (s int) {
	s = 1 + 2 + msgp.Float64Size + 2 + msgp.Float64Size
	return
}

// DecodeMsg implements msgp.Decodable
func (z *changeDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "checked":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Checked")
					return
				}
				z.Checked = nil
			} else {
				if z.Checked == nil {
					z.Checked = new(bool)
				}
				*z.Checked, err = dc.ReadBool()
				if err != nil {
					err = msgp.WrapError(err, "Checked")
					return
				}
			}
		case "value":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *changeDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.Checked == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "checked"
			err = en.Append(0xa7, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64)
			if err != nil {
				return
			}
			if z.Checked == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteBool(*z.Checked)
				if err != nil {
					err = msgp.WrapError(err, "Checked")
					return
				}
			}
		}
		// write "value"
		err = en.Append(0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Value)
		if err != nil {
			err = msgp.WrapError(err, "Value")
			return
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *changeDetail) Msgsize() (s int) {
	s = 1 + 8
	if z.Checked == nil {
		s += msgp.NilSize
	} else {
		s += msgp.BoolSize
	}
	s += 6 + msgp.StringPrefixSize + len(z.Value)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *clickDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "value":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		case "href":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Href")
					return
				}
				z.Href = nil
			} else {
				if z.Href == nil {
					z.Href = new(string)
				}
				*z.Href, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Href")
					return
				}
			}
		case "url":
			z.URL, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		case "area":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Area")
					return
				}
				z.Area = nil
			} else {
				if z.Area == nil {
					z.Area = new(Area)
				}
				err = z.Area.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Area")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *clickDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(4)
	var zb0001Mask uint8 /* 4 bits */
	_ = zb0001Mask
	if z.Value == "" {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.Href == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.URL == "" {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	if z.Area == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "value"
			err = en.Append(0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
			if err != nil {
				return
			}
			err = en.WriteString(z.Value)
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "href"
			err = en.Append(0xa4, 0x68, 0x72, 0x65, 0x66)
			if err != nil {
				return
			}
			if z.Href == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteString(*z.Href)
				if err != nil {
					err = msgp.WrapError(err, "Href")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "url"
			err = en.Append(0xa3, 0x75, 0x72, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteString(z.URL)
			if err != nil {
				err = msgp.WrapError(err, "URL")
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "area"
			err = en.Append(0xa4, 0x61, 0x72, 0x65, 0x61)
			if err != nil {
				return
			}
			if z.Area == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = z.Area.EncodeMsg(en)
				if err != nil {
					err = msgp.WrapError(err, "Area")
					return
				}
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *clickDetail) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Value) + 5
	if z.Href == nil {
		s += msgp.NilSize
	} else {
		s += msgp.StringPrefixSize + len(*z.Href)
	}
	s += 4 + msgp.StringPrefixSize + len(z.URL) + 5
	if z.Area == nil {
		s += msgp.NilSize
	} else {
		s += z.Area.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *dragDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			z.C, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "C")
				return
			}
		case "r":
			z.R, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "R")
				return
			}
		case "keys":
			var zb0002 uint32
			zb0002, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Keys")
				return
			}
			if cap(z.Keys) >= int(zb0002) {
				z.Keys = (z.Keys)[:zb0002]
			} else {
				z.Keys = make([]string, zb0002)
			}
			for za0001 := range z.Keys {
				z.Keys[za0001], err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Keys", za0001)
					return
				}
			}
		case "x":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "X")
					return
				}
				z.X = nil
			} else {
				if z.X == nil {
					z.X = new(int)
				}
				*z.X, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "X")
					return
				}
			}
		case "y":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Y")
					return
				}
				z.Y = nil
			} else {
				if z.Y == nil {
					z.Y = new(int)
				}
				*z.Y, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "Y")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *dragDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(5)
	var zb0001Mask uint8 /* 5 bits */
	_ = zb0001Mask
	if z.X == nil {
		zb0001Len--
		zb0001Mask |= 0x8
	}
	if z.Y == nil {
		zb0001Len--
		zb0001Mask |= 0x10
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "c"
		err = en.Append(0xa1, 0x63)
		if err != nil {
			return
		}
		err = en.WriteInt(z.C)
		if err != nil {
			err = msgp.WrapError(err, "C")
			return
		}
		// write "r"
		err = en.Append(0xa1, 0x72)
		if err != nil {
			return
		}
		err = en.WriteInt(z.R)
		if err != nil {
			err = msgp.WrapError(err, "R")
			return
		}
		// write "keys"
		err = en.Append(0xa4, 0x6b, 0x65, 0x79, 0x73)
		if err != nil {
			return
		}
		err = en.WriteArrayHeader(uint32(len(z.Keys)))
		if err != nil {
			err = msgp.WrapError(err, "Keys")
			return
		}
		for za0001 := range z.Keys {
			err = en.WriteString(z.Keys[za0001])
			if err != nil {
				err = msgp.WrapError(err, "Keys", za0001)
				return
			}
		}
		if (zb0001Mask & 0x8) == 0 { // if not omitted
			// write "x"
			err = en.Append(0xa1, 0x78)
			if err != nil {
				return
			}
			if z.X == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteInt(*z.X)
				if err != nil {
					err = msgp.WrapError(err, "X")
					return
				}
			}
		}
		if (zb0001Mask & 0x10) == 0 { // if not omitted
			// write "y"
			err = en.Append(0xa1, 0x79)
			if err != nil {
				return
			}
			if z.Y == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteInt(*z.Y)
				if err != nil {
					err = msgp.WrapError(err, "Y")
					return
				}
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *dragDetail) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize + 2 + msgp.IntSize + 5 + msgp.ArrayHeaderSize
	for za0001 := range z.Keys {
		s += msgp.StringPrefixSize + len(z.Keys[za0001])
	}
	s += 2
	if z.X == nil {
		s += msgp.NilSize
	} else {
		s += msgp.IntSize
	}
	s += 2
	if z.Y == nil {
		s += msgp.NilSize
	} else {
		s += msgp.IntSize
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *errorBody) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "code":
			z.Code, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Code")
				return
			}
		case "detail":
			z.Detail, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Detail")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z errorBody) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(2)
	var zb0001Mask uint8 /* 2 bits */
	_ = zb0001Mask
	if z.Detail == "" {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		// write "code"
		err = en.Append(0xa4, 0x63, 0x6f, 0x64, 0x65)
		if err != nil {
			return
		}
		err = en.WriteString(z.Code)
		if err != nil {
			err = msgp.WrapError(err, "Code")
			return
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "detail"
			err = en.Append(0xa6, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c)
			if err != nil {
				return
			}
			err = en.WriteString(z.Detail)
			if err != nil {
				err = msgp.WrapError(err, "Detail")
				return
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z errorBody) Msgsize() (s int) {
	s = 1 + 5 + msgp.StringPrefixSize + len(z.Code) + 7 + msgp.StringPrefixSize + len(z.Detail)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *fitDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "r":
			z.R, err = dc.ReadInt()
			if err != nil {
				err = msgp.WrapError(err, "R")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z fitDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "r"
	err = en.Append(0x81, 0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteInt(z.R)
	if err != nil {
		err = msgp.WrapError(err, "R")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z fitDetail) Msgsize() (s int) {
	s = 1 + 2 + msgp.IntSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *hoverDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "c":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
				z.C = nil
			} else {
				if z.C == nil {
					z.C = new(int)
				}
				*z.C, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
			}
		case "r":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "R")
					return
				}
				z.R = nil
			} else {
				if z.R == nil {
					z.R = new(int)
				}
				*z.R, err = dc.ReadInt()
				if err != nil {
					err = msgp.WrapError(err, "R")
					return
				}
			}
		case "out":
			z.Out, err = dc.ReadBool()
			if err != nil {
				err = msgp.WrapError(err, "Out")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *hoverDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(3)
	var zb0001Mask uint8 /* 3 bits */
	_ = zb0001Mask
	if z.C == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	if z.R == nil {
		zb0001Len--
		zb0001Mask |= 0x2
	}
	if z.Out == false {
		zb0001Len--
		zb0001Mask |= 0x4
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}

	// skip if no fields are to be emitted
	if zb0001Len != 0 {
		if (zb0001Mask & 0x1) == 0 { // if not omitted
			// write "c"
			err = en.Append(0xa1, 0x63)
			if err != nil {
				return
			}
			if z.C == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteInt(*z.C)
				if err != nil {
					err = msgp.WrapError(err, "C")
					return
				}
			}
		}
		if (zb0001Mask & 0x2) == 0 { // if not omitted
			// write "r"
			err = en.Append(0xa1, 0x72)
			if err != nil {
				return
			}
			if z.R == nil {
				err = en.WriteNil()
				if err != nil {
					return
				}
			} else {
				err = en.WriteInt(*z.R)
				if err != nil {
					err = msgp.WrapError(err, "R")
					return
				}
			}
		}
		if (zb0001Mask & 0x4) == 0 { // if not omitted
			// write "out"
			err = en.Append(0xa3, 0x6f, 0x75, 0x74)
			if err != nil {
				return
			}
			err = en.WriteBool(z.Out)
			if err != nil {
				err = msgp.WrapError(err, "Out")
				return
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *hoverDetail) Msgsize() (s int) {
	s = 1 + 2
	if z.C == nil {
		s += msgp.NilSize
	} else {
		s += msgp.IntSize
	}
	s += 2
	if z.R == nil {
		s += msgp.NilSize
	} else {
		s += msgp.IntSize
	}
	s += 4 + msgp.BoolSize
	return
}

// DecodeMsg implements msgp.Decodable
func (z *inputDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "value":
			z.Value, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "Value")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z inputDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 1
	// write "value"
	err = en.Append(0x81, 0xa5, 0x76, 0x61, 0x6c, 0x75, 0x65)
	if err != nil {
		return
	}
	err = en.WriteString(z.Value)
	if err != nil {
		err = msgp.WrapError(err, "Value")
		return
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z inputDetail) Msgsize() (s int) {
	s = 1 + 6 + msgp.StringPrefixSize + len(z.Value)
	return
}

// DecodeMsg implements msgp.Decodable
func (z *pressDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "area":
			if dc.IsNil() {
				err = dc.ReadNil()
				if err != nil {
					err = msgp.WrapError(err, "Area")
					return
				}
				z.Area = nil
			} else {
				if z.Area == nil {
					z.Area = new(Area)
				}
				err = z.Area.DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Area")
					return
				}
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *pressDetail) EncodeMsg(en *msgp.Writer) (err error) {
	// check for omitted fields
	zb0001Len := uint32(1)
	var zb0001Mask uint8 /* 1 bits */
	_ = zb0001Mask
	if z.Area == nil {
		zb0001Len--
		zb0001Mask |= 0x1
	}
	// variable map header, size zb0001Len
	err = en.Append(0x80 | uint8(zb0001Len))
	if err != nil {
		return
	}
	if (zb0001Mask & 0x1) == 0 { // if not omitted
		// write "area"
		err = en.Append(0xa4, 0x61, 0x72, 0x65, 0x61)
		if err != nil {
			return
		}
		if z.Area == nil {
			err = en.WriteNil()
			if err != nil {
				return
			}
		} else {
			err = z.Area.EncodeMsg(en)
			if err != nil {
				err = msgp.WrapError(err, "Area")
				return
			}
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *pressDetail) Msgsize() (s int) {
	s = 1 + 5
	if z.Area == nil {
		s += msgp.NilSize
	} else {
		s += z.Area.Msgsize()
	}
	return
}

// DecodeMsg implements msgp.Decodable
func (z *submitDetail) DecodeMsg(dc *msgp.Reader) (err error) {
	var zb0003 uint32
	zb0003, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	if (*z) == nil {
		(*z) = make(submitDetail, zb0003)
	} else if len((*z)) > 0 {
		clear((*z))
	}
	var field []byte
	_ = field
	for zb0003 > 0 {
		zb0003--
		var zb0001 string
		zb0001, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		var zb0002 string
		zb0002, err = dc.ReadString()
		if err != nil {
			err = msgp.WrapError(err, zb0001)
			return
		}
		(*z)[zb0001] = zb0002
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z submitDetail) EncodeMsg(en *msgp.Writer) (err error) {
	err = en.WriteMapHeader(uint32(len(z)))
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0004, zb0005 := range z {
		err = en.WriteString(zb0004)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		err = en.WriteString(zb0005)
		if err != nil {
			err = msgp.WrapError(err, zb0004)
			return
		}
	}
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z submitDetail) Msgsize() (s int) {
	s = msgp.MapHeaderSize
	if z != nil {
		for zb0004, zb0005 := range z {
			_ = zb0005
			s += msgp.StringPrefixSize + len(zb0004) + msgp.StringPrefixSize + len(zb0005)
		}
	}
	return
}
