package main

import (
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

const fixture = "testdata/fixture"

func generate(t *testing.T, root string) (*Module, map[string][]byte) {
	t.Helper()
	m, err := Load(root)
	if err != nil {
		t.Fatal(err)
	}
	files, err := m.Generate()
	if err != nil {
		t.Fatal(err)
	}
	return m, files
}

func keys(files map[string][]byte) []string {
	var out []string
	for k := range files {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func TestPackagesFound(t *testing.T) {
	m, files := generate(t, fixture)
	if m.Path != "example.com/fix" {
		t.Errorf("module path %q", m.Path)
	}
	// Internal packages and commands have no page; the root comes first.
	// (Large is documented by its group's comment.)
	want := []string{"README.md", "docs/api/README.md", "docs/api/fix.md", "docs/api/sub.md"}
	if got := keys(files); strings.Join(got, " ") != strings.Join(want, " ") {
		t.Errorf("files %v, want %v", got, want)
	}
	if m.Packages[0].Rel != "" || m.Packages[1].ImportPath != "example.com/fix/sub" {
		t.Errorf("order: %s, %s", m.Packages[0].ImportPath, m.Packages[1].ImportPath)
	}
}

func TestPage(t *testing.T) {
	_, files := generate(t, fixture)
	page := string(files["docs/api/fix.md"])
	for _, want := range []string{
		"<!-- Code generated by internal/docgen (make docs). DO NOT EDIT. -->\n\n# fix\n",
		"```go\nimport \"example.com/fix\"\n```",
		// Doc links: this page, the module's other pages, pkg.go.dev.
		"A [Thing](#Thing) holds an [sub.Item](sub.md#Item), and writes to a [strings.Builder](https://pkg.go.dev/strings#Builder).",
		"see [Thing.Quiet](#Thing.Quiet) and [Small](#Small).",
		// Headings keep an anchor GitHub knows.
		`### <a id="hdr-Usage"></a>Usage`,
		// Code blocks are fenced, as Go when they are.
		"```go\nt := fix.NewThing()\nt.Do()\n```",
		"```\n$ fix --now | cat\n```",
		// The index, with signatures.
		"- [`func Bare()`](#Bare)",
		"- [`type Thing`](#Thing)\n  - [`func NewThing() *Thing`](#NewThing)\n  - [`func (t *Thing) Do() string`](#Thing.Do)",
		// Values, an anchor for each name.
		`<a id="Small"></a><a id="Large"></a>`,
		"Small = 1 // a small thing",
		// Types without what is unexported, and their methods.
		"// Name is the thing's name.\n\tName string\n\t// contains filtered or unexported fields\n}",
		`### <a id="Thing.Do"></a>func (*Thing) Do`,
		`### <a id="NewThing"></a>func NewThing`,
		// Examples: the package's, with their doc, and a method's.
		"- [Package](#example-package)\n- [Package (Story)](#example-package-story)\n- [Thing.Do](#example-Thing.Do)",
		"### <a id=\"example-package-story\"></a>Example (Story)\n\nA story told by an example.\n\n```go\nt := fix.NewThing()\nfmt.Println(t.Do())\n```\n\nOutput:\n\n```\ndone\n```",
		"#### <a id=\"example-Thing.Do\"></a>Example\n\n```go\nfmt.Println(fix.NewThing().Do())\n```",
	} {
		if !strings.Contains(page, want) {
			t.Errorf("the page lacks:\n%s", want)
		}
	}
	if strings.Contains(page, "hidden int") || strings.Contains(page, "// Output") {
		t.Error("the page shows what is unexported, or an example's output comment")
	}
	sub := string(files["docs/api/sub.md"])
	if !strings.Contains(sub, "[fix.Thing](fix.md#Thing)") {
		t.Errorf("a link to the root package's page: %s", sub)
	}
}

func TestReadme(t *testing.T) {
	_, files := generate(t, fixture)
	readme := string(files["README.md"])
	want := "# fix\n\nWritten by hand.\n\n" +
		"<!-- docgen:packages -->\n| package | what it is |\n| --- | --- |\n" +
		"| [`fix`](docs/api/fix.md) | Package fix is a fixture for docgen's tests. |\n" +
		"| [`sub`](docs/api/sub.md) | Package sub holds items for fix.Thing. |\n" +
		"<!-- /docgen:packages -->\n\nAlso by hand.\n\n" +
		"<!-- docgen:examples -->\n| example | use case | what it shows |\n| --- | --- | --- |\n" +
		"| [hello](examples/hello) | Print a greeting to the terminal. | It shows the smallest program. |\n" +
		"| [nodoc](examples/nodoc) |  |  |\n" +
		"<!-- /docgen:examples -->\n"
	if readme != want {
		t.Errorf("README:\n%s\nwant:\n%s", readme, want)
	}
	index := string(files["docs/api/README.md"])
	if !strings.Contains(index, "| [`sub`](sub.md) | Package sub holds items for fix.Thing. |") {
		t.Errorf("docs/api/README.md:\n%s", index)
	}
}

func TestReplaceSection(t *testing.T) {
	ok := "a <!-- docgen:packages -->old<!-- /docgen:packages --> b"
	got, err := replaceSection([]byte(ok), packagesStart, packagesEnd, "new\n")
	if err != nil || string(got) != "a <!-- docgen:packages -->\nnew\n<!-- /docgen:packages --> b" {
		t.Errorf("%q, %v", got, err)
	}
	for name, src := range map[string]string{
		"no start":  "<!-- /docgen:packages -->",
		"no end":    "<!-- docgen:packages -->",
		"reversed":  "<!-- /docgen:packages --><!-- docgen:packages -->",
		"twice":     ok + ok,
		"no marker": "plain",
	} {
		if _, err := replaceSection([]byte(src), packagesStart, packagesEnd, "x"); err == nil {
			t.Errorf("%s: no error", name)
		}
	}
}

// copyDir copies a directory tree.
func copyDir(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, _ := filepath.Rel(src, p)
		out := filepath.Join(dst, rel)
		if d.IsDir() {
			return os.MkdirAll(out, 0o755)
		}
		b, err := os.ReadFile(p)
		if err != nil {
			return err
		}
		return os.WriteFile(out, b, 0o644)
	})
	if err != nil {
		t.Fatal(err)
	}
}

func TestChangesAndWrite(t *testing.T) {
	root := t.TempDir()
	copyDir(t, fixture, root)
	_, files := generate(t, root)
	changes, err := Changes(root, files)
	if err != nil {
		t.Fatal(err)
	}
	var got []string
	for _, c := range changes {
		got = append(got, c.String())
	}
	want := "changed README.md, new docs/api/README.md, new docs/api/fix.md, new docs/api/sub.md"
	if strings.Join(got, ", ") != want {
		t.Errorf("changes: %v", got)
	}
	if err := Write(root, files, changes); err != nil {
		t.Fatal(err)
	}
	// Written, nothing is left to change; a page no package has is removed.
	if err := os.WriteFile(filepath.Join(root, "docs/api/gone.md"), []byte("x"), 0o644); err != nil {
		t.Fatal(err)
	}
	_, files = generate(t, root)
	changes, err = Changes(root, files)
	if err != nil {
		t.Fatal(err)
	}
	if len(changes) != 1 || changes[0].String() != "removed docs/api/gone.md" {
		t.Fatalf("after writing: %v", changes)
	}
	if err := Write(root, files, changes); err != nil {
		t.Fatal(err)
	}
	if _, err := os.Stat(filepath.Join(root, "docs/api/gone.md")); !os.IsNotExist(err) {
		t.Error("the stale page is still there")
	}
}

func TestUndocumented(t *testing.T) {
	m, _ := generate(t, fixture)
	miss := m.Undocumented()
	if got := strings.Join(miss["example.com/fix"], " "); got != "Loose Bare Thing.Quiet" {
		t.Errorf("undocumented: %q", got)
	}
	if _, ok := miss["example.com/fix/sub"]; ok {
		t.Errorf("sub is documented: %v", miss)
	}
}

func TestFirstSentence(t *testing.T) {
	for in, want := range map[string]string{
		"One. Two.":                  "One.",
		"Use e.g. this. Then that.":  "Use e.g.", // as go/doc has it
		"Ask U.S. people. Then.":     "Ask U.S. people.",
		"Really? Yes.":               "Really?",
		"No end":                     "No end",
		"Version 0.1 is out. Later.": "Version 0.1 is out.",
	} {
		if got := firstSentence(in); got != want {
			t.Errorf("firstSentence(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestAssumedName(t *testing.T) {
	for in, want := range map[string]string{
		"github.com/neuroplastio/hotty-go": "hotty",
		"charm.land/bubbletea/v2":          "bubbletea",
		"github.com/x/go-thing":            "thing",
		"gopkg.in/yaml.v3":                 "yaml",
		"strings":                          "strings",
	} {
		if got := assumedName(in); got != want {
			t.Errorf("assumedName(%q) = %q, want %q", in, got, want)
		}
	}
}

func TestCodeLang(t *testing.T) {
	for code, want := range map[string]string{
		"x := 1\nfmt.Println(x)": "go",
		"func F() {}":            "go",
		"if !ok {\n\t...\n}":     "go",
		"f(xs...)":               "go",
		"$ make check":           "",
		"ESC ] 7279 ; a=q ST":    "",
	} {
		if got := codeLang(code); got != want {
			t.Errorf("codeLang(%q) = %q, want %q", code, got, want)
		}
	}
}

// The module's own documentation, as checked in, is what docgen writes.
func TestDocsAreCurrent(t *testing.T) {
	_, files := generate(t, "../..")
	changes, err := Changes("../..", files)
	if err != nil {
		t.Fatal(err)
	}
	for _, c := range changes {
		t.Errorf("%s: run make docs", c)
	}
}

// Every exported identifier of the module's public packages has a doc
// comment.
func TestEveryExportedIdentifierIsDocumented(t *testing.T) {
	m, _ := generate(t, "../..")
	miss := m.Undocumented()
	var pkgs []string
	for p := range miss {
		pkgs = append(pkgs, p)
	}
	sort.Strings(pkgs)
	for _, p := range pkgs {
		t.Errorf("%s: no doc comment on %s", p, strings.Join(miss[p], ", "))
	}
}

var (
	anchorRE = regexp.MustCompile(`<a id="([^"]+)"></a>`)
	linkRE   = regexp.MustCompile(`\]\(([^)\s]+)\)`)
	// codeRE is code, fenced or a span, whose brackets are not links: an
	// Example's Markdown in a Go string.
	codeRE = regexp.MustCompile("(?s)```.*?```|`[^`\n]*`")
)

// Every link the documentation makes inside the repository leads to a file
// that is there, and to an anchor on it.
func TestLinksResolve(t *testing.T) {
	for _, root := range []string{fixture, "../.."} {
		_, files := generate(t, root)
		anchors := map[string]map[string]bool{}
		for p, b := range files {
			anchors[p] = map[string]bool{}
			for _, m := range anchorRE.FindAllStringSubmatch(string(b), -1) {
				anchors[p][m[1]] = true
			}
		}
		for p, b := range files {
			for _, m := range linkRE.FindAllStringSubmatch(codeRE.ReplaceAllString(string(b), ""), -1) {
				target := m[1]
				if strings.Contains(target, "://") {
					continue
				}
				file, frag, _ := strings.Cut(target, "#")
				if file == "" {
					file = p
				} else {
					file = filepath.ToSlash(filepath.Join(filepath.Dir(p), file))
				}
				if _, ok := files[file]; !ok {
					if _, err := os.Stat(filepath.Join(root, file)); err != nil {
						t.Errorf("%s: %s: %s is not there", root, p, target)
					}
					continue
				}
				if frag != "" && !anchors[file][frag] {
					t.Errorf("%s: %s: no anchor for %s", root, p, target)
				}
			}
		}
	}
}
