package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/doc"
	"go/doc/comment"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"sort"
	"strings"
	"unicode"
	"unicode/utf8"
)

// notice heads every file docgen writes in full.
const notice = "<!-- Code generated by internal/docgen (make docs). DO NOT EDIT. -->\n"

// renderer writes one package's page.
type renderer struct {
	m      *Module
	p      *Package
	parser *comment.Parser
	print  *comment.Printer
	b      bytes.Buffer
}

func (m *Module) newRenderer(p *Package) *renderer {
	r := &renderer{m: m, p: p}
	r.parser = p.Doc.Parser()
	std := r.parser.LookupPackage
	r.parser.LookupPackage = func(name string) (string, bool) {
		// The package's own imports, then the module's packages, then
		// the standard library.
		if ip, ok := p.imports[name]; ok {
			return ip, true
		}
		if ip, ok := m.names[name]; ok {
			return ip, true
		}
		if std != nil {
			return std(name)
		}
		return comment.DefaultLookupPackage(name)
	}
	r.print = &comment.Printer{DocLinkURL: r.linkURL}
	return r
}

// linkURL is where a doc link goes: an anchor on this page, a page of
// docs/api for the module's packages, or pkg.go.dev for the rest.
func (r *renderer) linkURL(l *comment.DocLink) string {
	frag := l.Name
	if l.Recv != "" {
		frag = l.Recv + "." + l.Name
	}
	ip := l.ImportPath
	if ip == "" || ip == r.p.ImportPath {
		if frag == "" {
			return "#pkg-overview"
		}
		return "#" + frag
	}
	for _, q := range r.m.Packages {
		if q.ImportPath == ip {
			u := pageName(q.Rel, q.Doc.Name)
			if frag != "" {
				u += "#" + frag
			}
			return u
		}
	}
	u := "https://pkg.go.dev/" + ip
	if frag != "" {
		u += "#" + frag
	}
	return u
}

// markdown renders a doc comment. Headings carry an anchor GitHub keeps
// (the printer's {#id} is not Markdown it knows), and code blocks are
// fenced, as Go when they parse as Go.
func (r *renderer) markdown(text string, level int) string {
	d := r.parser.Parse(text)
	var out []string
	for _, blk := range d.Content {
		switch x := blk.(type) {
		case *comment.Heading:
			title := strings.TrimSpace(string(r.print.Markdown(&comment.Doc{
				Content: []comment.Block{&comment.Paragraph{Text: x.Text}}, Links: d.Links})))
			title = strings.TrimPrefix(title, `\`) // the printer escapes a leading '#'
			out = append(out, fmt.Sprintf(`%s <a id="%s"></a>%s`, strings.Repeat("#", level), x.DefaultID(), title))
		case *comment.Code:
			code := strings.TrimRight(x.Text, "\n")
			out = append(out, "```"+codeLang(code)+"\n"+code+"\n```")
		default:
			s := string(r.print.Markdown(&comment.Doc{Content: []comment.Block{blk}, Links: d.Links}))
			out = append(out, strings.TrimRight(s, "\n"))
		}
	}
	return strings.Join(out, "\n\n")
}

// codeLang is "go" for a code block that parses as Go: declarations, or
// statements. A line of nothing but "..." or "…" stands for code left out.
func codeLang(code string) string {
	lines := strings.Split(code, "\n")
	for i, l := range lines {
		if t := strings.TrimSpace(l); t == "..." || t == "…" {
			lines[i] = "_ = 0"
		}
	}
	code = strings.Join(lines, "\n")
	fset := token.NewFileSet()
	if _, err := parser.ParseFile(fset, "", "package p\n"+code, 0); err == nil {
		return "go"
	}
	if _, err := parser.ParseFile(fset, "", "package p\nfunc _() {\n"+code+"\n}", 0); err == nil {
		return "go"
	}
	return ""
}

func (r *renderer) w(format string, args ...any) { fmt.Fprintf(&r.b, format, args...) }

// source prints a declaration as gofmt would, without its doc comment,
// with the comments of its fields and specs.
func (r *renderer) source(node ast.Node) string {
	var b bytes.Buffer
	switch d := node.(type) {
	case *ast.FuncDecl:
		c := *d
		c.Doc, c.Body = nil, nil
		_ = format.Node(&b, r.p.Fset, &c)
	case *ast.GenDecl:
		c := *d
		c.Doc = nil
		var groups []*ast.CommentGroup
		add := func(g *ast.CommentGroup) {
			if g != nil && g != d.Doc {
				groups = append(groups, g)
			}
		}
		ast.Inspect(d, func(n ast.Node) bool {
			switch x := n.(type) {
			case *ast.Field:
				add(x.Doc)
				add(x.Comment)
			case *ast.ValueSpec:
				add(x.Doc)
				add(x.Comment)
			case *ast.TypeSpec:
				add(x.Doc)
				add(x.Comment)
			}
			return true
		})
		sort.Slice(groups, func(i, j int) bool { return groups[i].Pos() < groups[j].Pos() })
		_ = format.Node(&b, r.p.Fset, &printer.CommentedNode{Node: &c, Comments: groups})
		if incomplete(d) {
			// The printer loses its own note when given the comments.
			src := strings.TrimRight(b.String(), "\n }")
			b.Reset()
			b.WriteString(src + "\n\t// contains filtered or unexported fields\n}")
		}
	default:
		_ = format.Node(&b, r.p.Fset, node)
	}
	return b.String()
}

// incomplete reports a type declared alone whose struct or interface lost
// fields or methods that are not exported.
func incomplete(d *ast.GenDecl) bool {
	if d.Tok != token.TYPE || len(d.Specs) != 1 {
		return false
	}
	switch t := d.Specs[0].(*ast.TypeSpec).Type.(type) {
	case *ast.StructType:
		return t.Incomplete
	case *ast.InterfaceType:
		return t.Incomplete
	}
	return false
}

// signature is a function's declaration on one line, for the index.
func (r *renderer) signature(f *doc.Func) string {
	return strings.Join(strings.Fields(r.source(f.Decl)), " ")
}

// code is a fenced Go block.
func code(src string) string { return "```go\n" + strings.TrimRight(src, "\n") + "\n```\n\n" }

// page renders the package's page.
func (r *renderer) page() []byte {
	p := r.p.Doc
	r.w("%s\n# %s\n\n", notice, p.Name)
	r.w("```go\nimport %q\n```\n\n", r.p.ImportPath)
	if p.Doc == "" {
		r.w("%s\n\n", "(No package comment.)")
	}
	r.w("- [Overview](#pkg-overview)\n- [Index](#pkg-index)\n")
	if exs := r.allExamples(); len(exs) > 0 {
		r.w("- [Examples](#pkg-examples)\n")
	}
	r.w("\n## <a id=\"pkg-overview\"></a>Overview\n\n")
	if p.Doc != "" {
		r.w("%s\n\n", r.markdown(p.Doc, 3))
	}
	for _, ex := range p.Examples {
		r.example(ex, "", 3)
	}
	r.index()
	if len(p.Consts) > 0 {
		r.w("## <a id=\"pkg-constants\"></a>Constants\n\n")
		for _, v := range p.Consts {
			r.value(v)
		}
	}
	if len(p.Vars) > 0 {
		r.w("## <a id=\"pkg-variables\"></a>Variables\n\n")
		for _, v := range p.Vars {
			r.value(v)
		}
	}
	for _, f := range p.Funcs {
		r.fn(f, "", 2)
	}
	for _, t := range p.Types {
		r.typ(t)
	}
	return bytes.TrimRight(r.b.Bytes(), "\n")
}

func (r *renderer) index() {
	p := r.p.Doc
	r.w("## <a id=\"pkg-index\"></a>Index\n\n")
	if len(p.Consts) > 0 {
		r.w("- [Constants](#pkg-constants)\n")
	}
	if len(p.Vars) > 0 {
		r.w("- [Variables](#pkg-variables)\n")
	}
	for _, f := range p.Funcs {
		r.w("- [`%s`](#%s)\n", r.signature(f), f.Name)
	}
	for _, t := range p.Types {
		r.w("- [`type %s`](#%s)\n", t.Name, t.Name)
		for _, f := range t.Funcs {
			r.w("  - [`%s`](#%s)\n", r.signature(f), f.Name)
		}
		for _, f := range t.Methods {
			r.w("  - [`%s`](#%s.%s)\n", r.signature(f), t.Name, f.Name)
		}
	}
	r.w("\n")
	if exs := r.allExamples(); len(exs) > 0 {
		r.w("### <a id=\"pkg-examples\"></a>Examples\n\n")
		for _, e := range exs {
			r.w("- [%s](#%s)\n", e.title, e.id)
		}
		r.w("\n")
	}
}

// value renders a group of constants or variables, with an anchor for
// each name.
func (r *renderer) value(v *doc.Value) {
	for _, n := range v.Names {
		if token.IsExported(n) {
			r.w("<a id=\"%s\"></a>", n)
		}
	}
	r.w("\n\n%s", code(r.source(v.Decl)))
	if v.Doc != "" {
		r.w("%s\n\n", r.markdown(v.Doc, 4))
	}
}

// fn renders a function or a method of recv.
func (r *renderer) fn(f *doc.Func, recv string, level int) {
	h := strings.Repeat("#", level)
	if recv == "" {
		r.w("%s <a id=\"%s\"></a>func %s\n\n", h, f.Name, f.Name)
	} else {
		r.w("%s <a id=\"%s.%s\"></a>func (%s) %s\n\n", h, recv, f.Name, f.Recv, f.Name)
	}
	r.w("%s", code(r.source(f.Decl)))
	if f.Doc != "" {
		r.w("%s\n\n", r.markdown(f.Doc, level+1))
	}
	owner := f.Name
	if recv != "" {
		owner = recv + "." + f.Name
	}
	for _, ex := range f.Examples {
		r.example(ex, owner, level+1)
	}
}

func (r *renderer) typ(t *doc.Type) {
	r.w("## <a id=\"%s\"></a>type %s\n\n", t.Name, t.Name)
	r.w("%s", code(r.source(t.Decl)))
	if t.Doc != "" {
		r.w("%s\n\n", r.markdown(t.Doc, 3))
	}
	for _, ex := range t.Examples {
		r.example(ex, t.Name, 3)
	}
	for _, v := range t.Consts {
		r.value(v)
	}
	for _, v := range t.Vars {
		r.value(v)
	}
	for _, f := range t.Funcs {
		r.fn(f, "", 3)
	}
	for _, f := range t.Methods {
		r.fn(f, t.Name, 3)
	}
}

// exampleRef is an example in the index.
type exampleRef struct{ title, id string }

// exampleID is an example's anchor, as pkg.go.dev has them: example-Name,
// example-Type.Method, example-package-Suffix, example-Name-Suffix.
func exampleID(owner, suffix string) string {
	id := "example-" + owner
	if owner == "" {
		id = "example-package"
	}
	if suffix != "" {
		id += "-" + suffix
	}
	return id
}

func exampleTitle(owner, suffix string) string {
	t := owner
	if owner == "" {
		t = "Package"
	}
	if suffix != "" {
		t += " (" + upperFirst(suffix) + ")"
	}
	return t
}

func upperFirst(s string) string {
	r, n := utf8.DecodeRuneInString(s)
	return string(unicode.ToUpper(r)) + s[n:]
}

// allExamples lists the package's examples in the order of the page.
func (r *renderer) allExamples() []exampleRef {
	p := r.p.Doc
	var out []exampleRef
	add := func(owner string, exs []*doc.Example) {
		for _, e := range exs {
			out = append(out, exampleRef{exampleTitle(owner, e.Suffix), exampleID(owner, e.Suffix)})
		}
	}
	add("", p.Examples)
	for _, f := range p.Funcs {
		add(f.Name, f.Examples)
	}
	for _, t := range p.Types {
		add(t.Name, t.Examples)
		for _, f := range t.Funcs {
			add(f.Name, f.Examples)
		}
		for _, f := range t.Methods {
			add(t.Name+"."+f.Name, f.Examples)
		}
	}
	return out
}

// example renders an Example function: its doc, its code and its output.
func (r *renderer) example(ex *doc.Example, owner string, level int) {
	title := "Example"
	if ex.Suffix != "" {
		title += " (" + upperFirst(ex.Suffix) + ")"
	}
	r.w("%s <a id=\"%s\"></a>%s\n\n", strings.Repeat("#", level), exampleID(owner, ex.Suffix), title)
	if ex.Doc != "" {
		r.w("%s\n\n", r.markdown(ex.Doc, level+1))
	}
	r.w("%s", code(r.exampleCode(ex)))
	if ex.Output != "" || ex.EmptyOutput {
		label := "Output:"
		if ex.Unordered {
			label = "Output, in any order:"
		}
		r.w("%s\n\n```\n%s\n```\n\n", label, strings.TrimRight(ex.Output, "\n"))
	}
}

// exampleCode is an example's body, without its braces and its output
// comment; a whole-file example is its runnable program.
func (r *renderer) exampleCode(ex *doc.Example) string {
	var b bytes.Buffer
	if _, whole := ex.Code.(*ast.File); whole && ex.Play != nil {
		_ = format.Node(&b, r.p.Fset, ex.Play)
		return b.String()
	}
	_ = format.Node(&b, r.p.Fset, &printer.CommentedNode{Node: ex.Code, Comments: ex.Comments})
	src := b.String()
	if _, block := ex.Code.(*ast.BlockStmt); !block {
		return src
	}
	src = strings.TrimSpace(src)
	src = strings.TrimSuffix(strings.TrimPrefix(src, "{"), "}")
	var lines []string
	for _, l := range strings.Split(strings.Trim(src, "\n"), "\n") {
		t := strings.TrimSpace(l)
		if strings.HasPrefix(t, "// Output:") || strings.HasPrefix(t, "// Unordered output:") {
			break
		}
		lines = append(lines, strings.TrimPrefix(l, "\t"))
	}
	return strings.TrimRight(strings.Join(lines, "\n"), "\n ")
}
