// Code generated by go test -run TestDrawGenerated -update; DO NOT EDIT.

package hottyvt

// drawCSS draws the drawn characters (draw.go).
const drawCSS = `.vt { --vt-l: max(1px, 0.07em); }
.vt-k { display: inline-block; position: relative; vertical-align: top; overflow: hidden; letter-spacing: 0;
  width: calc(var(--vt-n, 1) * var(--vt-scale) * var(--hotty-cell-w)); height: calc(var(--vt-scale) * var(--hotty-cell-h));
  -webkit-text-fill-color: transparent;
  --vt-al: 0; --vt-ar: 0; --vt-au: 0; --vt-ad: 0;
  --vt-h: max(var(--vt-al), var(--vt-ar)); --vt-v: max(var(--vt-au), var(--vt-ad));
  --vt-b1: var(--vt-l) solid; --vt-b2: calc(2 * var(--vt-l)) solid; --vt-b3: calc(3 * var(--vt-l)) double;
  --vt-c1: calc(50% - var(--vt-l) / 2); --vt-c2: calc(50% - var(--vt-l)); --vt-c3: calc(50% - 1.5 * var(--vt-l));
  --vt-r: calc(var(--vt-scale) * var(--hotty-cell-w) / 2); --vt-q: linear-gradient(currentColor, currentColor); }
.vt-k::before, .vt-k::after { content: ""; position: absolute; box-sizing: border-box; border: 0 solid; }
.vt-k::before { left: calc((1 - min(var(--vt-al), 1)) * (50% - var(--vt-v) * var(--vt-l) / 2));
  right: calc((1 - min(var(--vt-ar), 1)) * (50% - var(--vt-v) * var(--vt-l) / 2));
  top: calc(50% - var(--vt-h) * var(--vt-l) / 2); border-top: calc(var(--vt-h) * var(--vt-l)) var(--vt-hs, solid); }
.vt-k::after { top: calc((1 - min(var(--vt-au), 1)) * (50% - var(--vt-h) * var(--vt-l) / 2));
  bottom: calc((1 - min(var(--vt-ad), 1)) * (50% - var(--vt-h) * var(--vt-l) / 2));
  left: calc(50% - var(--vt-v) * var(--vt-l) / 2); border-left: calc(var(--vt-v) * var(--vt-l)) var(--vt-vs, solid); }
.vt-k2500{--vt-al:1;--vt-ar:1}
.vt-k2501{--vt-al:2;--vt-ar:2}
.vt-k2502{--vt-au:1;--vt-ad:1}
.vt-k2503{--vt-au:2;--vt-ad:2}
.vt-k250c{--vt-ar:1;--vt-ad:1}
.vt-k250d{--vt-ar:2;--vt-ad:1}
.vt-k250e{--vt-ar:1;--vt-ad:2}
.vt-k250f{--vt-ar:2;--vt-ad:2}
.vt-k2510{--vt-al:1;--vt-ad:1}
.vt-k2511{--vt-al:2;--vt-ad:1}
.vt-k2512{--vt-al:1;--vt-ad:2}
.vt-k2513{--vt-al:2;--vt-ad:2}
.vt-k2514{--vt-ar:1;--vt-au:1}
.vt-k2515{--vt-ar:2;--vt-au:1}
.vt-k2516{--vt-ar:1;--vt-au:2}
.vt-k2517{--vt-ar:2;--vt-au:2}
.vt-k2518{--vt-al:1;--vt-au:1}
.vt-k2519{--vt-al:2;--vt-au:1}
.vt-k251a{--vt-al:1;--vt-au:2}
.vt-k251b{--vt-al:2;--vt-au:2}
.vt-k251c{--vt-ar:1;--vt-au:1;--vt-ad:1}
.vt-k251d{--vt-ar:2;--vt-au:1;--vt-ad:1}
.vt-k251e{--vt-ar:1;--vt-au:2;--vt-ad:1}
.vt-k251f{--vt-ar:1;--vt-au:1;--vt-ad:2}
.vt-k2520{--vt-ar:1;--vt-au:2;--vt-ad:2}
.vt-k2521{--vt-ar:2;--vt-au:2;--vt-ad:1}
.vt-k2522{--vt-ar:2;--vt-au:1;--vt-ad:2}
.vt-k2523{--vt-ar:2;--vt-au:2;--vt-ad:2}
.vt-k2524{--vt-al:1;--vt-au:1;--vt-ad:1}
.vt-k2525{--vt-al:2;--vt-au:1;--vt-ad:1}
.vt-k2526{--vt-al:1;--vt-au:2;--vt-ad:1}
.vt-k2527{--vt-al:1;--vt-au:1;--vt-ad:2}
.vt-k2528{--vt-al:1;--vt-au:2;--vt-ad:2}
.vt-k2529{--vt-al:2;--vt-au:2;--vt-ad:1}
.vt-k252a{--vt-al:2;--vt-au:1;--vt-ad:2}
.vt-k252b{--vt-al:2;--vt-au:2;--vt-ad:2}
.vt-k252c{--vt-al:1;--vt-ar:1;--vt-ad:1}
.vt-k252d{--vt-al:2;--vt-ar:1;--vt-ad:1}
.vt-k252e{--vt-al:1;--vt-ar:2;--vt-ad:1}
.vt-k252f{--vt-al:2;--vt-ar:2;--vt-ad:1}
.vt-k2530{--vt-al:1;--vt-ar:1;--vt-ad:2}
.vt-k2531{--vt-al:2;--vt-ar:1;--vt-ad:2}
.vt-k2532{--vt-al:1;--vt-ar:2;--vt-ad:2}
.vt-k2533{--vt-al:2;--vt-ar:2;--vt-ad:2}
.vt-k2534{--vt-al:1;--vt-ar:1;--vt-au:1}
.vt-k2535{--vt-al:2;--vt-ar:1;--vt-au:1}
.vt-k2536{--vt-al:1;--vt-ar:2;--vt-au:1}
.vt-k2537{--vt-al:2;--vt-ar:2;--vt-au:1}
.vt-k2538{--vt-al:1;--vt-ar:1;--vt-au:2}
.vt-k2539{--vt-al:2;--vt-ar:1;--vt-au:2}
.vt-k253a{--vt-al:1;--vt-ar:2;--vt-au:2}
.vt-k253b{--vt-al:2;--vt-ar:2;--vt-au:2}
.vt-k253c{--vt-al:1;--vt-ar:1;--vt-au:1;--vt-ad:1}
.vt-k253d{--vt-al:2;--vt-ar:1;--vt-au:1;--vt-ad:1}
.vt-k253e{--vt-al:1;--vt-ar:2;--vt-au:1;--vt-ad:1}
.vt-k253f{--vt-al:2;--vt-ar:2;--vt-au:1;--vt-ad:1}
.vt-k2540{--vt-al:1;--vt-ar:1;--vt-au:2;--vt-ad:1}
.vt-k2541{--vt-al:1;--vt-ar:1;--vt-au:1;--vt-ad:2}
.vt-k2542{--vt-al:1;--vt-ar:1;--vt-au:2;--vt-ad:2}
.vt-k2543{--vt-al:2;--vt-ar:1;--vt-au:2;--vt-ad:1}
.vt-k2544{--vt-al:1;--vt-ar:2;--vt-au:2;--vt-ad:1}
.vt-k2545{--vt-al:2;--vt-ar:1;--vt-au:1;--vt-ad:2}
.vt-k2546{--vt-al:1;--vt-ar:2;--vt-au:1;--vt-ad:2}
.vt-k2547{--vt-al:2;--vt-ar:2;--vt-au:2;--vt-ad:1}
.vt-k2548{--vt-al:2;--vt-ar:2;--vt-au:1;--vt-ad:2}
.vt-k2549{--vt-al:2;--vt-ar:1;--vt-au:2;--vt-ad:2}
.vt-k254a{--vt-al:1;--vt-ar:2;--vt-au:2;--vt-ad:2}
.vt-k254b{--vt-al:2;--vt-ar:2;--vt-au:2;--vt-ad:2}
.vt-k2550{--vt-al:3;--vt-ar:3;--vt-hs:double}
.vt-k2551{--vt-au:3;--vt-ad:3;--vt-vs:double}
.vt-k2552::before{left:var(--vt-c1);right:0;border-left:var(--vt-b1);top:var(--vt-c3);bottom:0;border-top:var(--vt-b3)}
.vt-k2553::before{left:var(--vt-c3);right:0;border-left:var(--vt-b3);top:var(--vt-c1);bottom:0;border-top:var(--vt-b1)}
.vt-k2554::before{left:var(--vt-c3);right:0;border-left:var(--vt-b3);top:var(--vt-c3);bottom:0;border-top:var(--vt-b3)}
.vt-k2555::before{left:0;right:var(--vt-c1);border-right:var(--vt-b1);top:var(--vt-c3);bottom:0;border-top:var(--vt-b3)}
.vt-k2556::before{left:0;right:var(--vt-c3);border-right:var(--vt-b3);top:var(--vt-c1);bottom:0;border-top:var(--vt-b1)}
.vt-k2557::before{left:0;right:var(--vt-c3);border-right:var(--vt-b3);top:var(--vt-c3);bottom:0;border-top:var(--vt-b3)}
.vt-k2558::before{left:var(--vt-c1);right:0;border-left:var(--vt-b1);top:0;bottom:var(--vt-c3);border-bottom:var(--vt-b3)}
.vt-k2559::before{left:var(--vt-c3);right:0;border-left:var(--vt-b3);top:0;bottom:var(--vt-c1);border-bottom:var(--vt-b1)}
.vt-k255a::before{left:var(--vt-c3);right:0;border-left:var(--vt-b3);top:0;bottom:var(--vt-c3);border-bottom:var(--vt-b3)}
.vt-k255b::before{left:0;right:var(--vt-c1);border-right:var(--vt-b1);top:0;bottom:var(--vt-c3);border-bottom:var(--vt-b3)}
.vt-k255c::before{left:0;right:var(--vt-c3);border-right:var(--vt-b3);top:0;bottom:var(--vt-c1);border-bottom:var(--vt-b1)}
.vt-k255d::before{left:0;right:var(--vt-c3);border-right:var(--vt-b3);top:0;bottom:var(--vt-c3);border-bottom:var(--vt-b3)}
.vt-k255e{--vt-ar:3;--vt-au:1;--vt-ad:1;--vt-hs:double}
.vt-k255f{--vt-ar:1;--vt-au:3;--vt-ad:3;--vt-vs:double}
.vt-k2560{--vt-ar:3;--vt-au:3;--vt-ad:3;--vt-hs:double;--vt-vs:double}
.vt-k2561{--vt-al:3;--vt-au:1;--vt-ad:1;--vt-hs:double}
.vt-k2562{--vt-al:1;--vt-au:3;--vt-ad:3;--vt-vs:double}
.vt-k2563{--vt-al:3;--vt-au:3;--vt-ad:3;--vt-hs:double;--vt-vs:double}
.vt-k2564{--vt-al:3;--vt-ar:3;--vt-ad:1;--vt-hs:double}
.vt-k2565{--vt-al:1;--vt-ar:1;--vt-ad:3;--vt-vs:double}
.vt-k2566{--vt-al:3;--vt-ar:3;--vt-ad:3;--vt-hs:double;--vt-vs:double}
.vt-k2567{--vt-al:3;--vt-ar:3;--vt-au:1;--vt-hs:double}
.vt-k2568{--vt-al:1;--vt-ar:1;--vt-au:3;--vt-vs:double}
.vt-k2569{--vt-al:3;--vt-ar:3;--vt-au:3;--vt-hs:double;--vt-vs:double}
.vt-k256a{--vt-al:3;--vt-ar:3;--vt-au:1;--vt-ad:1;--vt-hs:double}
.vt-k256b{--vt-al:1;--vt-ar:1;--vt-au:3;--vt-ad:3;--vt-vs:double}
.vt-k256c{--vt-al:3;--vt-ar:3;--vt-au:3;--vt-ad:3;--vt-hs:double;--vt-vs:double}
.vt-k256d::before{left:var(--vt-c1);right:0;border-left:var(--vt-b1);top:var(--vt-c1);bottom:0;border-top:var(--vt-b1);border-top-left-radius:var(--vt-r)}
.vt-k256e::before{left:0;right:var(--vt-c1);border-right:var(--vt-b1);top:var(--vt-c1);bottom:0;border-top:var(--vt-b1);border-top-right-radius:var(--vt-r)}
.vt-k256f::before{left:0;right:var(--vt-c1);border-right:var(--vt-b1);top:0;bottom:var(--vt-c1);border-bottom:var(--vt-b1);border-bottom-right-radius:var(--vt-r)}
.vt-k2570::before{left:var(--vt-c1);right:0;border-left:var(--vt-b1);top:0;bottom:var(--vt-c1);border-bottom:var(--vt-b1);border-bottom-left-radius:var(--vt-r)}
.vt-k2574{--vt-al:1}
.vt-k2575{--vt-au:1}
.vt-k2576{--vt-ar:1}
.vt-k2577{--vt-ad:1}
.vt-k2578{--vt-al:2}
.vt-k2579{--vt-au:2}
.vt-k257a{--vt-ar:2}
.vt-k257b{--vt-ad:2}
.vt-k257c::before{left:0;right:50%;top:var(--vt-c1);bottom:auto;border-top:var(--vt-b1)}
.vt-k257c::after{left:50%;right:0;top:var(--vt-c2);bottom:auto;border-top:var(--vt-b2)}
.vt-k257d::before{top:0;bottom:50%;left:var(--vt-c1);right:auto;border-left:var(--vt-b1)}
.vt-k257d::after{top:50%;bottom:0;left:var(--vt-c2);right:auto;border-left:var(--vt-b2)}
.vt-k257e::before{left:0;right:50%;top:var(--vt-c2);bottom:auto;border-top:var(--vt-b2)}
.vt-k257e::after{left:50%;right:0;top:var(--vt-c1);bottom:auto;border-top:var(--vt-b1)}
.vt-k257f::before{top:0;bottom:50%;left:var(--vt-c2);right:auto;border-left:var(--vt-b2)}
.vt-k257f::after{top:50%;bottom:0;left:var(--vt-c1);right:auto;border-left:var(--vt-b1)}
.vt-k2580{background:linear-gradient(currentColor 50%, transparent 0)}
.vt-k2581{background:linear-gradient(transparent 87.5%, currentColor 0)}
.vt-k2582{background:linear-gradient(transparent 75%, currentColor 0)}
.vt-k2583{background:linear-gradient(transparent 62.5%, currentColor 0)}
.vt-k2584{background:linear-gradient(transparent 50%, currentColor 0)}
.vt-k2585{background:linear-gradient(transparent 37.5%, currentColor 0)}
.vt-k2586{background:linear-gradient(transparent 25%, currentColor 0)}
.vt-k2587{background:linear-gradient(transparent 12.5%, currentColor 0)}
.vt-k2588{background:currentColor}
.vt-k2589{background:linear-gradient(to right, currentColor 87.5%, transparent 0)}
.vt-k258a{background:linear-gradient(to right, currentColor 75%, transparent 0)}
.vt-k258b{background:linear-gradient(to right, currentColor 62.5%, transparent 0)}
.vt-k258c{background:linear-gradient(to right, currentColor 50%, transparent 0)}
.vt-k258d{background:linear-gradient(to right, currentColor 37.5%, transparent 0)}
.vt-k258e{background:linear-gradient(to right, currentColor 25%, transparent 0)}
.vt-k258f{background:linear-gradient(to right, currentColor 12.5%, transparent 0)}
.vt-k2590{background:linear-gradient(to right, transparent 50%, currentColor 0)}
.vt-k2591{background:color-mix(in srgb, currentColor 25%, transparent)}
.vt-k2592{background:color-mix(in srgb, currentColor 50%, transparent)}
.vt-k2593{background:color-mix(in srgb, currentColor 75%, transparent)}
.vt-k2594{background:linear-gradient(currentColor 12.5%, transparent 0)}
.vt-k2595{background:linear-gradient(to right, transparent 87.5%, currentColor 0)}
.vt-k2596{background:var(--vt-q) 0 100%/50% 50% no-repeat}
.vt-k2597{background:var(--vt-q) 100% 100%/50% 50% no-repeat}
.vt-k2598{background:var(--vt-q) 0 0/50% 50% no-repeat}
.vt-k2599{background:var(--vt-q) 0 0/50% 50% no-repeat,var(--vt-q) 0 100%/50% 50% no-repeat,var(--vt-q) 100% 100%/50% 50% no-repeat}
.vt-k259a{background:var(--vt-q) 0 0/50% 50% no-repeat,var(--vt-q) 100% 100%/50% 50% no-repeat}
.vt-k259b{background:var(--vt-q) 0 0/50% 50% no-repeat,var(--vt-q) 100% 0/50% 50% no-repeat,var(--vt-q) 0 100%/50% 50% no-repeat}
.vt-k259c{background:var(--vt-q) 0 0/50% 50% no-repeat,var(--vt-q) 100% 0/50% 50% no-repeat,var(--vt-q) 100% 100%/50% 50% no-repeat}
.vt-k259d{background:var(--vt-q) 100% 0/50% 50% no-repeat}
.vt-k259e{background:var(--vt-q) 100% 0/50% 50% no-repeat,var(--vt-q) 0 100%/50% 50% no-repeat}
.vt-k259f{background:var(--vt-q) 100% 0/50% 50% no-repeat,var(--vt-q) 0 100%/50% 50% no-repeat,var(--vt-q) 100% 100%/50% 50% no-repeat}
`

// drawnRunes are the characters drawn; tilingRunes, those of them that draw
// alike in every cell.
const (
	drawnRunes  = "─━│┃┌┍┎┏┐┑┒┓└┕┖┗┘┙┚┛├┝┞┟┠┡┢┣┤┥┦┧┨┩┪┫┬┭┮┯┰┱┲┳┴┵┶┷┸┹┺┻┼┽┾┿╀╁╂╃╄╅╆╇╈╉╊╋═║╒╓╔╕╖╗╘╙╚╛╜╝╞╟╠╡╢╣╤╥╦╧╨╩╪╫╬╭╮╯╰╴╵╶╷╸╹╺╻╼╽╾╿▀▁▂▃▄▅▆▇█▉▊▋▌▍▎▏▐░▒▓▔▕▖▗▘▙▚▛▜▝▞▟"
	tilingRunes = "─━═▀▁▂▃▄▅▆▇█░▒▓▔"
)
